name: bohurupifit
description: A modern fitness workout app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  provider: ^6.0.5
  cached_network_image: ^3.3.0
  flutter_animate: ^4.2.0
  shared_preferences: ^2.2.1
  intl: ^0.20.1
  flutter_svg: ^2.0.7
  flutter_staggered_animations: ^1.1.1
  http: ^1.1.0
  path_provider: ^2.1.2
  flutter_cache_manager: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - json/
    - assets/images/
